/**
 * Mirrors UpDownMessingI_1_4_20.cpp: giantArrayToHoldNotes (lines 128–140)
 * and translatedToScaleArray (lines 150–186).
 */

/**
 * @param {{ numNotes: number; step: number; jump: number }[]} rows
 * @param {number} startNote
 * @param {number} numRepeats
 * @returns {number[]}
 */
// each row taken from user input will have 
// "numNotes" for a row is the # of notes that will be generated by the row operation
// "step" is the size of the jump up or down from the start note
// "jump" is the last operation of a row that specifies 
//  where the next row operation's start note will be in relation to the last of the current row's notes
// 
// if start note is 48
// and numNotes is 3 (the start note counts as 1 of the notes so will produce 2 additional notes to the start note)
// and step is 2
// and jump is -3
// then will have the notes 48, 50, 52
// and will apply jump of -3 to have the last note or 1st note of the next row operation 
// to be 49
// 48, 50, 52, 49 
export function buildGiantArray(rows, startNote, numRepeats) {
  const giant = [];
  const numArrays = rows.length;
  if (numArrays === 0 || numRepeats <= 0) {
    return giant;
  }

  let s = startNote;
  // apply operations for as many rows of operations there are * the # of repeats
  for (let b = 0; b < numArrays * numRepeats; b++) {
    const row = rows[b % numArrays]; // get current row's values
    const numNotes = row.numNotes; // # of notes to generate in this operation
    const step = row.step; // size of move (can be positive or negative)
    const jump = row.jump; // jump size at end of this operation to start note of next operation
    for (let a = 0; a < numNotes; a++) {
      giant.push(s); // go ahead and push the start note
      s += step; // apply the move to the next note for the next iteration
    }
    // set 1st note for next row's operation to start on
    // need to remove last step that was applied in for loop
    s = s + jump - step; 
  }
  return giant;
}

/**
 * @param {number[]} giant
 * @param {number} startNoteCopy
 * @param {number[]} scaleArray
 * @returns {number[]}
 */
// now translate the notes calculated in buildGiantArray to notes that the user specified in their scale
// giant was initially constructed starting at the start note
// and moving +1, -1, +2, -2 etc. in magnitude 
// but not through scale degrees like if (48, 50, 52, 54, 55, 57, 59)
// then + 2 would be from 48 to the 2nd scale degree 52
export function translateToScale(giant, startNoteCopy, scaleArray) {
  const ScaleArraySize = scaleArray.length;
  if (ScaleArraySize === 0) {
    throw new Error("Scale array must be non-empty.");
  }

  const translated = [];
  for (let a = 0; a < giant.length; a++) {
    let ANote;
    let Octaves;
    let ScaleArrayIndex;
    let NegNote;
    let NewNote;
    let ANoteRelativeToStartNote;

    // if moving to a lower note
    if (giant[a] - startNoteCopy < 0) {
      // get the negative distance from the start note 
      NegNote = giant[a] - startNoteCopy; 
      // make it positive 
      ANote = NegNote * -1;
      // to find the octave distance from the start note
      Octaves = Math.trunc(ANote / ScaleArraySize);
      // get the index of the scale array to translate to
      ScaleArrayIndex = ANote % ScaleArraySize;

      // if the index is 0, then we are on a note in the scale and can just place it in the correct octave
      if (ScaleArrayIndex === 0) {
        ANote = -(Octaves * 12);
      } 
      else { // if the index is not 0, then we need to find the note in the scale array to translate to and place it in the correct octave
        ScaleArrayIndex = ScaleArraySize - ScaleArrayIndex;
        ANote = -(12 - scaleArray[ScaleArrayIndex]) - Octaves * 12;
      }
      // add back the start note to get the final translated note
      ANote = ANote + startNoteCopy;
      translated[a] = ANote;
    } 
    else { // moving to a higher note
      ANote = giant[a];
      ANoteRelativeToStartNote = ANote - startNoteCopy;
      // find octave distance from start note
      Octaves = Math.trunc(ANoteRelativeToStartNote / ScaleArraySize);
      // get index of scale array to translate to
      ScaleArrayIndex = ANoteRelativeToStartNote % ScaleArraySize;
      // get new note from scale array and place in correct octave
      NewNote = scaleArray[ScaleArrayIndex] + startNoteCopy + Octaves * 12;
      translated[a] = NewNote;
    }
  }
  return translated;
}

/**
 * @param {number[]} arr
 * @returns {string}
 */
// return comma separated string to display to screen
export function formatNoteArray(arr) {
  return arr.map((n) => String(n)).join(", ") + "\n";
}
